#!/bin/bash
#### lnmp-70 v1.0.0
## rkhunter new hash. rkhunterがスキャンする際に利用するハッシュの新規生成。
#
source ./default.txt
####
cat <<EOF > /home/${USER_NAME}/check.sh
#!/bin/bash
sudo sh /etc/cron.weekly/clamscan
sudo sh /etc/cron.daily/public
sudo sh /etc/cron.daily/tripwire.sh
sudo rkhunter --update
sudo rkhunter --propupd
sudo rkhunter --check --skip-keypress
EOF
vim /home/${USER_NAME}/check.sh
chmod +x /home/${USER_NAME}/check.sh
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/check.sh
####
sh /home/${USER_NAME}/check.sh
ls -la
############################################################################
#### 作業が完全に終わりましたら、不要になったセットアップファイル群は削除して下さい。
############################################################################