#!/bin/bash
#### lnmp-72 v1.0.7
############################################################################
## rkhunter new hash. rkhunterがスキャンする際に利用するハッシュの新規生成。
#
source ./initfile
####
rm -f ${INSTALL_PATH}/*.sh
rm -f ${INSTALL_PATH}/{*.txt,*.md,.gitignore,startup}
rm -fr ${INSTALL_PATH}/{ReverseProxy,text,.git}
####
yum clean all
####
cat <<EOF > /home/${USER_NAME}/check.sh
#!/bin/bash
sh /etc/cron.daily/clamscan
sh /etc/cron.daily/public
sh /etc/cron.daily/tripwire.sh
rkhunter --update
rkhunter --propupd
echo -e "rootkit チェックしますか？ [y/n]"
echo -e "rootkit check? [y/n]"
read checkrootkit
# Rootkit Check.
if [ \${checkrootkit} = "y" ] ; then
rkhunter --check --skip-keypress
fi
EOF
vim /home/${USER_NAME}/check.sh
chmod +x /home/${USER_NAME}/check.sh
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/check.sh
####
sh /home/${USER_NAME}/check.sh
ls -la
############################################################################
#### 作業が完全に終わりましたら、不要になったセットアップファイル群は削除して下さい。
############################################################################