#!/bin/bash
#### lnmp-70 v0.0.1
source ./initfile
####
chmod 400 ${INSTALL_PATH}/initfile
chmod 400 ${INSTALL_PATH}/last_optimization
##############################################
#echo -e "LAMP(Linux, Apache, MariaDB, PHP)でインストールしますか？ [y] \n"
echo -e "LNMP(Linux, Nginx, MariaDB, PHP7.0)でインストールしますか？ [y] \n"
read instaltolamp
##############################################
if [ ${instaltolamp} = "y" ] ; then
### LAMP Mode Install Start.
### Nginx+Apache Mode Install Start.
##############################################
ln -s ${INSTALL_PATH}/ReverseProxy/01-network-setup ${INSTALL_PATH}/NA01-NET.sh
ln -s ${INSTALL_PATH}/ReverseProxy/02-repository-setup ${INSTALL_PATH}/NA02-REPO.sh
ln -s ${INSTALL_PATH}/ReverseProxy/03-program-setup ${INSTALL_PATH}/NA03-SOFT.sh
ln -s ${INSTALL_PATH}/ReverseProxy/04-nginx-php-fpm-setup ${INSTALL_PATH}/NA04-WEBSV.sh
ln -s ${INSTALL_PATH}/ReverseProxy/05-database-setup ${INSTALL_PATH}/NA05-DB.sh
chmod -R +x ${INSTALL_PATH}/{NA01-NET.sh,NA02-REPO.sh,NA03-SOFT.sh,NA04-WEBSV.sh,NS04_5-NGXBUILD.sh,NA05-DB.sh}
##############################################
fi