#!/bin/bash
#### lnmp-70 v1.0.0
source ./initfile.txt
####
chmod 600 ${INSTALL_PATH}/initfile.txt
chmod 600 ${INSTALL_PATH}/text/*.txt
ln -s ${INSTALL_PATH}/text/default.txt ${INSTALL_PATH}/default.txt
ln -s ${INSTALL_PATH}/text/server.txt ${INSTALL_PATH}/server.txt
ln -s ${INSTALL_PATH}/text/cms.txt ${INSTALL_PATH}/cms.txt
ln -s ${INSTALL_PATH}/text/nginx-build.txt ${INSTALL_PATH}/nginx-build.txt
chmod 400 ${INSTALL_PATH}/last_optimization
##############################################
#echo -e "LAMP(Linux, Apache, MariaDB, PHP)でインストールしますか？ [y] \n"
echo -e "LNMP(Linux, Nginx, MariaDB, PHP7.0)でインストールしますか？ [y] \n"
read instaltolamp
##############################################
if [ ${instaltolamp} = "y" ] ; then
### LAMP Mode Install Start.
### Nginx+Apache Mode Install Start.
##############################################
ln -s ${INSTALL_PATH}/ReverseProxy/01-default-setup ${INSTALL_PATH}/NA01-DEF.sh
ln -s ${INSTALL_PATH}/ReverseProxy/02-server-setup ${INSTALL_PATH}/NA02-WEB.sh
ln -s ${INSTALL_PATH}/ReverseProxy/03-cms-setup ${INSTALL_PATH}/NA03-CMS.sh
chmod -R +x ${INSTALL_PATH}/{NA01-DEF.sh,NA02-WEB.sh,NA03-CMS.sh,NGXBUILD.sh}
##############################################
fi