#!/bin/bash
#### lnmp-72 v1.0.6
source ./initfile
####
chmod 600 ${INSTALL_PATH}/initfile
##############################################
ln -s ${INSTALL_PATH}/text/nginx-build.txt ${INSTALL_PATH}/nginx-build.txt
ln -s ${INSTALL_PATH}/text/base.txt ${INSTALL_PATH}/base.txt
ln -s ${INSTALL_PATH}/text/server.txt ${INSTALL_PATH}/server.txt
ln -s ${INSTALL_PATH}/text/cms.txt ${INSTALL_PATH}/cms.txt
ln -s ${INSTALL_PATH}/text/deny_spam.txt ${INSTALL_PATH}/deny_spam.txt
ln -s ${INSTALL_PATH}/text/config_init.txt ${INSTALL_PATH}/config_init.txt
##############################################
chmod 600 ${INSTALL_PATH}/text/*.txt
chmod 400 ${INSTALL_PATH}/last_optimization
##############################################
#echo -e "LAMP(Linux, Apache, MariaDB, PHP)でインストールしますか？ [y]"
echo -e "Jp: LNMP(Linux, Nginx, MariaDB, PHP7.0 or PHP5.6)？ [y]"
echo -e "En: LNMP(Linux, Nginx, MariaDB, PHP7.0 or PHP5.6)? [y]"
read instaltolamp
##############################################
if [ ${instaltolamp} = "y" ] ; then
### LAMP Mode Install Start.
### Nginx+Apache Mode Install Start.
##############################################
ln -s ${INSTALL_PATH}/Webserver/01-default-setup ${INSTALL_PATH}/01.DEFAULT-SETUP.sh
ln -s ${INSTALL_PATH}/Webserver/02-server-setup ${INSTALL_PATH}/O2.WEBSERVER-SETUP.sh
ln -s ${INSTALL_PATH}/Webserver/03-cms-setup ${INSTALL_PATH}/03.DB-SETUP.sh
chmod -R +x ${INSTALL_PATH}/*.sh
##############################################
fi