#!/bin/sh
#### lnmp-70 v0.0.1
############################################################################
source ./initfile
############################################################################
## SELINUXの変更。SakuraVPSでは既に disabled されているのでデフォルトで n を選択して下さい。
echo -e "SELINUXの変更を開始します。[y] \n"
echo -e "既に一回このシェルを通している場合は [n] \n"
read opt_install06
if [ ${opt_install06} = "y" ] ; then
getenforce
echo "インストール先でSELINUXは有効化されてましたか？ [y/n] : さくらのVPSなら='n'"
read selinuxenforcing
if [ ${selinuxenforcing} = "y" ] ; then
	setenforce 0
	getenforce
echo "SELINUXを完全に無効化しますか？ [y/n]"
read selinuxdisabled
if [ ${selinuxdisabled} = "y" ] ; then
	sed -i 's|^SELINUX=enforcing$|SELINUX=disabled|g' /etc/selinux/config
else
	sed -i 's|^SELINUX=enforcing$|SELINUX=permissive|g' /etc/selinux/config
fi
	vi /etc/selinux/config
	vi /etc/sysconfig/selinux
	yum install selinux-policy-targeted selinux-policy-devel
	# SSH Port
	semanage port -l | grep ssh
	semanage port -a -t ssh_port_t -p tcp ${SSH_EDIT_PORT}
	semanage port -l | grep ssh
	# HTTP Port
	semanage port -l | grep http
	semanage port -a -t http_cache_port_t -p tcp ${REVERSE_PROXY_PORT}
	semanage port -l | grep http
fi
#
fi
############################################################################
#### リポジトリの追加。
############################################################################
#
echo -e "CentOS7専用のリポジトリを追加します。[y] \n"
echo -e "既に一回このシェルを通している場合は [n] \n"
read opt_install07
if [ ${opt_install07} = "y" ] ; then
## Rpmforge Repository
echo -e "CentOS7専用のリポジトリを追加します。"
rpm --import ${RepoRPMForgeGPG}
rpm -ivh ${RepoRPMForgex86}
#
## Epel Repository
rpm --import ${RepoEpelGPG}
rpm -ivh ${RepoEPELx86}
#
## Elrepo Repository
rpm --import ${RepoElrepoGPG}
rpm -ivh ${RepoElrepox86}
#
## Remi Repository
rpm --import ${RepoRemiGPG}
rpm -ivh ${RepoRemix86}
#
############################################################################
#
vi /etc/yum.repos.d/rpmforge.repo
## clamd-0.98.4 and clamav-0.98.7 / Conflict.
sed -i "8a\exclude=clam*" /etc/yum.repos.d/epel.repo
vi /etc/yum.repos.d/epel.repo
vi /etc/yum.repos.d/elrepo.repo
vi /etc/yum.repos.d/remi.repo
#
## 各リリースのアップデート
yum -y update rpmforge-release epel-release elrepo-release remi-release
#
fi
############################################################################
#### yumアップデート、グループインストール、yum-cronのインストール。
############################################################################
#
echo -e "yumアップデート、グループインストール、yum-cronのインストールを開始します。[y] \n"
echo -e "既に一回このシェルを通している場合は [n] \n"
read opt_install08
if [ ${opt_install08} = "y" ] ; then
yum -y update
yum -y install git mercurial etckeeper
touch /etc/.gitignore
echo "shadow*" >> /etc/.gitignore
echo "gshadow*" >> /etc/.gitignore
echo "passwd*" >> /etc/.gitignore
echo "group*" >> /etc/.gitignore
yum -y groupinstall "Base" "Development tools" "Japanese Support"
#
## yum-cron install
yum -y install yum-cron
systemctl enable yum-cron
systemctl start yum-cron
# etckeeper init
etckeeper init
etckeeper commit "VPS Installed First Commit."
#
fi
############################################################################
#### portsentry install. - Portスキャンをされた場合、拒否するソフトウェアを追加。
############################################################################
#
echo -e "portsentryのインストールを開始します。[y] \n"
echo -e "既に一回このシェルを通している場合は [n] \n"
read opt_install09
if [ ${opt_install09} = "y" ] ; then
wget http://ftp.riken.go.jp/Linux/freshrpms/redhat/9/portsentry/portsentry-1.1-fr8.src.rpm
rpmbuild --rebuild portsentry-1.1-fr8.src.rpm
rm -f portsentry-1.1-fr8.src.rpm
rpm -ivh /root/rpmbuild/RPMS/*/portsentry*.rpm
rm -f /root/rpmbuild/RPMS/*/portsentry*.rpm
rm -fr /root/rpmbuild
#
############################################################################
#### KILL_HOSTS_DENY. - 設定ファイルを編集。
############################################################################
#
sed -i 's|^#KILL_HOSTS_DENY="ALL: $TARGET$ : DENY"$|KILL_HOSTS_DENY="ALL: $TARGET$ : DENY"|g' /etc/portsentry/portsentry.conf
vi /etc/portsentry/portsentry.conf
#
############################################################################
#### portsentry WhiteList Edit. - ホワイトリストに自身の接続するIPAddrを追加する。
############################################################################
#
echo "Portsentry WhiteList のインストール先はローカルですか？ [y/n]"
read porthosts
if [ ${porthosts} = "y" ] ; then
	# ローカル接続での接続IPを書き込む
	echo "${LOCAL_IP_ADDR}" >> /etc/portsentry/portsentry.ignore
else
	echo "接続先は固定IPですか？ [y/n]"
	read globalstaticip

	if [ ${globalstaticip} = "y" ] ; then
		# グローバル接続での固定IPを書き込む
		echo "${GLOBAL_IP_ADDR}" >> /etc/portsentry/portsentry.ignore
	else
		echo "IPアドレス以外でのホワイトリストの設定されません。"
	fi
fi
vi /etc/portsentry/portsentry.ignore
#
/sbin/chkconfig portsentry on
fi
############################################################################
#### denyhosts install. Denyhosts の追加。
############################################################################
#
echo -e "denyhostsのインストールを開始します。\n"
yum -y install denyhosts
#
############################################################################
#
systemctl enable denyhosts
systemctl start denyhosts
#
############################################################################
#### Password Expect Install. 後に設定するパスワードを生成。事前にDLしておく。
############################################################################
echo -e "expectのインストールを開始します。\n"
yum -y install expect
#mkpasswd -s 0 -C 8 -d 8 -l 32 > /home/${USER_NAME}/${MYSQLPASSWDDIR}/sqladmin.txt
#mkpasswd -s 0 -C 8 -d 8 -l 32 > /home/${USER_NAME}/${MYSQLPASSWDDIR}/sqluser.txt
############################################################################
##  引き続き、sh ../secure/secure を実行してください。
############################################################################