#!/bin/bash
#### lnmp-70 v1.0.1
############################################################################
source ./initfile.txt
source ./default.txt
source ./server.txt
############################################################################
echo -e "Jp: WebServer(Nginx)をインストールします。[y] / 既に一回このシェルを通している場合は [n]"
echo -e "En: It will install the WebServer (Nginx). [y] / Already one time when it is passed through the shell [n]"
read set_webserver_inst
if [ ${set_webserver_inst} = "y" ] ; then
# CentOS7 httpd normal install.
yum -y install pcre-devel \
zlib-devel \
openssl-devel \
libxslt-devel \
GeoIP-devel \
gd-devel \
perl-ExtUtils-Embed \
gperftools-devel \
httpd-devel \
httpd \
mod_ssl
clear
echo -e "Jp: ここで一度、別のターミナルを立ち上げてください。"
echo -e "Jp: ユーザ権限でSSHログインし NGXBUILD.sh を実行して Nginx をビルドして下さい。"
echo -e "En: Here once, please launch another terminal."
echo -e "En: Build your Nginx by running the SSH login NGXBUILD.sh in user permissions."
#### PHP Install.
echo -e "Jp: PHP7.x をインストールする場合は [y] / PHP5.6 をインストールする場合は [n]"
echo -e "En: If you want to install PHP7.x [y] / If you want to install the PHP5.6 [n]"
read DEFPHPINST_70_56
if [ ${DEFPHPINST_70_56} = "y" ] ; then
echo -e "Jp: PHP7.x をインストールします"
echo -e "En: It will install the PHP7.x"
yum --enablerepo=remi,remi-php70 install php \
php-cli \
php-devel \
php-mbstring \
php-gd \
php-pear \
php-xml \
php-pecl-apc \
php-mcrypt \
php-mysqli \
php-pecl-zip \
mariadb \
mariadb-server \
php-fpm
else
echo -e "Jp: PHP5.6 をインストールします"
echo -e "En: It will install the PHP5.6"
yum --enablerepo=remi,remi-php56 install php \
php-cli \
php-devel \
php-mbstring \
php-gd \
php-pear \
php-xml \
php-pecl-apc \
php-mcrypt \
php-mysqli \
php-pecl-zip \
mariadb \
mariadb-server \
php-fpm
fi
####
fi
clear
echo -e "Jp: PHP-FPMをセットアップします。"
echo -e "En: It will set up the PHP-FPM."
cp /etc/php-fpm.d/www.conf /etc/php-fpm.d/www_conf.origin
vim /etc/php-fpm.d/www.conf
echo -e "PHP-FPM Edit."
sed -i "s|^listen = 127.0.0.1:9000|listen = ${BACKEND_LISTEN_SOCK}|g" /etc/php-fpm.d/www.conf
sed -i 's|^listen.allowed_clients = 127.0.0.1|;\0|' /etc/php-fpm.d/www.conf
sed -i "s|^;listen.owner = nobody|listen.owner = ${WEB_SERVER_SYSTEM_USER_GROUP}|g" /etc/php-fpm.d/www.conf
sed -i "s|^;listen.group = nobody|listen.group = ${WEB_SERVER_SYSTEM_USER_GROUP}|g" /etc/php-fpm.d/www.conf
sed -i "s|^user = apache$|user = ${WEB_SERVER_SYSTEM_USER_GROUP}|g" /etc/php-fpm.d/www.conf
sed -i "s|^group = apache$|group = ${WEB_SERVER_SYSTEM_USER_GROUP}|g" /etc/php-fpm.d/www.conf
sed -i 's|^;listen.mode|listen.mode|g' /etc/php-fpm.d/www.conf
sed -i 's|^pm = dynamic|pm = static|g' /etc/php-fpm.d/www.conf
sed -i "s|^pm.max_children = 50|pm.max_children = 10|g" /etc/php-fpm.d/www.conf
sed -i "s|^;pm.max_requests = 500|pm.max_requests = 500|g" /etc/php-fpm.d/www.conf
vim /etc/php-fpm.d/www.conf
# PHP.ini Edit
#
echo -e "Jp: PHP.iniを編集します。"
echo -e "En: You will edit the PHP.ini."
sed -i "s|^memory_limit = 128M|memory_limit = ${PHP_MEM_LIMIT}|g" /etc/php.ini
sed -i "s|^post_max_size = 8M|post_max_size = ${PHP_POST_MAX}|g" /etc/php.ini
sed -i "s|^upload_max_filesize = 2M|upload_max_filesize = ${PHP_UPLOAD_MAX}|g" /etc/php.ini
sed -i "s|^expose_php = On|expose_php = ${PHP_EXPOSE}|g" /etc/php.ini
sed -i "s|^;date.timezone =|date.timezone = \"${PHP_DATE_TIMEZONE}\"|g" /etc/php.ini
sed -i "s|^;session.cookie_secure =|session.cookie_secure = ${PHP_SESSION_COOKIE}|g" /etc/php.ini
sed -i "s|^session.cookie_domain =|;\0|g" /etc/php.ini
vim /etc/php.ini
####
clear
echo -e "Jp: Apacheをセットアップします。[y] / 既に一回このシェルを通している場合は [n]"
echo -e "En: You set up the Apache. [y] / Already one time when it is passed through the shell [n]"
read optserverinst02
if [ ${optserverinst02} = "y" ] ; then
#########################################
echo -e "Apache Backend Setup."
# httpd.conf Edit.
echo -e "httpd.conf Edit."
sed -i "s|^Listen 80$|Listen ${BACKEND_LISTEN_PORT}|g" ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
sed -i 's|Options Indexes FollowSymLinks$|Options -Indexes +FollowSymLinks|g' ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
sed -i "s|^ErrorLog \"logs/error_log\"$|ErrorLog \"${APACHE_LOG_DIRECTORY}/httpd_error_log\"|g" ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
sed -i "s|CustomLog \"logs/access_log\" combined$|CustomLog \"${APACHE_LOG_DIRECTORY}/httpd_access_log\" combined|g" ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
sed -i "s|^User apache$|User ${WEB_SERVER_SYSTEM_USER_GROUP}|g" ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
sed -i "s|^Group apache$|Group ${WEB_SERVER_SYSTEM_USER_GROUP}|g" ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
echo "ServerTokens Prod" >> ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
echo "KeepAlive On" >> ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
echo "ServerSignature Off" >> ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
vim ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
#
# 00-base.conf Edit.
echo -e "00-base.conf Edit."
sed -i 's|^LoadModule authn_anon_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-base.conf
sed -i 's|^LoadModule authn_dbm_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-base.conf
sed -i 's|^LoadModule authz_owner_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-base.conf
sed -i 's|^LoadModule authz_dbm_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-base.conf
sed -i 's|^LoadModule status_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-base.conf
sed -i 's|^LoadModule userdir_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-base.conf
sed -i 's|^LoadModule cache_disk_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-base.conf
vim ${APACHE_MOD_CONFIG_DIRECTORY}/00-base.conf
#
# 00-dev.conf Edit.
echo -e "00-dev.conf Edit."
sed -i 's|^LoadModule dav_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-dav.conf
sed -i 's|^LoadModule dav_fs_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-dav.conf
sed -i 's|^LoadModule dav_lock_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-dav.conf
vim ${APACHE_MOD_CONFIG_DIRECTORY}/00-dav.conf
#
# 00-proxy.conf Edit.
echo -e "00-proxy.conf Edit."
sed -i 's|^LoadModule lbmethod_bybusyness_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule lbmethod_byrequests_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule lbmethod_bytraffic_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule lbmethod_heartbeat_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_express_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_fcgi_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_fdpass_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_scgi_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_balancer_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_ftp_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_http_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_ajp_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_connect_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
sed -i 's|^LoadModule proxy_wstunnel_module|#\0|' ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
vim ${APACHE_MOD_CONFIG_DIRECTORY}/00-proxy.conf
#
# extract_forwarded Buile.
echo -e "extract_forwarded Build."
cd /usr/local/src
git clone ${APACHE_MOD_EXTRACT_FORWARDED} extract_forwarded
cd /usr/local/src/extract_forwarded
apxs -i -c -a mod_extract_forwarded.c
cd /usr/local/src/
rm -rf extract_forwarded
#
# 99-nginx.conf Create.
echo -e "99-nginx.conf Create."
cat <<EOF > ${APACHE_MOD_CONFIG_DIRECTORY}/99-nginx.conf
# Proxy Mod Conflict
LoadModule extract_forwarded_module modules/mod_extract_forwarded.so
# Nginx IP Address
MEForder refuse,accept
MEFrefuse all
# Nginx Local IP
MEFaccept 127.0.0.1
EOF
vim ${APACHE_MOD_CONFIG_DIRECTORY}/99-nginx.conf
#
# extract_forwarded Comment Out.
echo -e "extract_forwarded Comment Out."
sed -i 's|^LoadModule extract_forwarded_module /usr/lib64/httpd/modules/mod_extract_forwarded.so$|#\0|g' ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
vim ${APACHE_BASE_CONFIG_DIRECTORY}/httpd.conf
#
# welcome.conf Edit.
echo -e "welcome.conf Edit."
sed -i 's|^<LocationMatch|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^    Options -Indexes|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^    ErrorDocument|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^</LocationMatch>|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^<Directory /usr/share/httpd/noindex>|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^    AllowOverride None|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^    Require all granted|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^</Directory>|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^Alias /.noindex.html /usr/share/httpd/noindex/index.html|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^Alias /noindex/css/bootstrap.min.css /usr/share/httpd/noindex/css/bootstrap.min.css|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^Alias /noindex/css/open-sans.css /usr/share/httpd/noindex/css/open-sans.css|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^Alias /images/apache_pb.gif /usr/share/httpd/noindex/images/apache_pb.gif|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
sed -i 's|^Alias /images/poweredby.png /usr/share/httpd/noindex/images/poweredby.png|#\0|' ${APACHE_CONFIG_DIRECTORY}/welcome.conf
vim ${APACHE_CONFIG_DIRECTORY}/welcome.conf
mkdir -p /var/www/{html,logs,error,icons,cgi-bin}
touch /var/www/error/{401.html,403.html,404.html,500.html,index.html}
echo "401 - Authorization Required." >> /var/www/error/401.html
echo "403 - Forbidden." >> /var/www/error/403.html
echo "404 - Not Found." >> /var/www/error/404.html
echo "500 - Internal Server Error." >> /var/www/error/500.html
chown -R ${WEB_SERVER_SYSTEM_USER_GROUP}:${WEB_SERVER_SYSTEM_USER_GROUP} /var/www/{html,logs,error,icons,cgi-bin}
chown -R ${WEB_SERVER_SYSTEM_USER_GROUP}:${WEB_SERVER_SYSTEM_USER_GROUP} /var/lib/php/session
# Create domain.conf
echo -e "${CONFIG_HOST_DOMAIN}.conf Create."
cat <<EOF > ${APACHE_CONFIG_DIRECTORY}/${CONFIG_HOST_DOMAIN}.conf
# DocumentRoot
<VirtualHost ${BACKEND_SERVER_PORT}>
  ServerName ${CONFIG_HOST_DOMAIN}:${BACKEND_LISTEN_PORT}
  DocumentRoot ${APACHE_FILE_DIRECTORY}
  ServerAdmin info@localhost
  ErrorLog ${APACHE_LOG_DIRECTORY}/httpd_${CONFIG_HOST_DOMAIN}_proxy_error_log
  TransferLog ${APACHE_LOG_DIRECTORY}/httpd_${CONFIG_HOST_DOMAIN}_proxy_access_log
  #<FilesMatch \.php$>
  #    SetHandler "proxy:unix:/var/run/php-fpm/php-fpm.sock|fcgi://localhost"
  #</FilesMatch>
</VirtualHost>
EOF
#
vim ${APACHE_CONFIG_DIRECTORY}/${CONFIG_HOST_DOMAIN}.conf
mv ${APACHE_CONFIG_DIRECTORY}/ssl.conf ${APACHE_CONFIG_DIRECTORY}/ssl_conf
######################################################################
# GeoIP DB Directory
######################################################################
echo -e "GeoIP DB Directory Setup."
#
cd ${GEOIP_PATH}
# GeoIP.dat mv GeoIP.dat.YYYYmmdd-IMS.bak
mv ${GEOIP_FILE} ${GEOIP_FILE}."$(date +%Y%m%d-%I%M%S).bak"
# GeoIP New Get Files
wget ${GEOIP_URL}/${GEOIP_FILE}.gz
# GeoIP.dat Gunzip
gunzip ${GEOIP_FILE}.gz
cd ${INSTALL_PATH}
####
cat <<EOF > /etc/cron.weekly/GeoIP
#!/bin/bash
# GeoIP DB Directory
cd ${GEOIP_PATH}
# GeoIP.dat mv GeoIP.dat.YYYYmmdd-IMS.bak
mv ${GEOIP_FILE} ${GEOIP_FILE}."\$(date +%Y%m%d-%I%M%S).bak"
# GeoIP New Get Files
wget ${GEOIP_URL}/${GEOIP_FILE}.gz
# GeoIP.dat Gunzip
gunzip ${GEOIP_FILE}.gz
cd
# Apache Nginx restart
systemctl restart php-fpm
systemctl restart nginx
EOF
vim /etc/cron.weekly/GeoIP
chmod +x /etc/cron.weekly/GeoIP
####
fi
######################################################################
echo -e "Jp: Nginxをセットアップします。[y] / 既に一回このシェルを通している場合は [n]"
echo -e "En: You set up the Nginx. [y] / Already one time when it is passed through the shell [n]"
read set_nginx_setup
if [ ${set_nginx_setup} = "y" ] ; then
######################################################################
# Default Setting.
######################################################################
echo -e "Nginx Default Setting."
sed -i "s|^user nginx|user ${WEB_SERVER_SYSTEM_USER_GROUP}|g" /etc/nginx/nginx.conf
#sed -i "s|^worker_processes 1|worker_processes ${NGINX_WORKER_PROCESSES}|g" /etc/nginx.conf
sed -i "s|^worker_processes 1|worker_processes $(cat /proc/cpuinfo | grep processor | wc -l)|g" /etc/nginx.conf
sed -i "3a\#worker_cpu_affinity ${NGINX_WORKER_CPU_AFFINITY};" /etc/nginx/nginx.conf
sed -i "4a\#worker_priority ${NGINX_WORKER_PRIORITY};" /etc/nginx/nginx.conf
sed -i "s|^error_log /var/log/nginx/error.log|error_log ${APACHE_LOG_DIRECTORY}/nginx_error.log|g" /etc/nginx/nginx.conf
sed -i "s|access_log  /var/log/nginx/access.log  main|access_log  ${APACHE_LOG_DIRECTORY}/nginx_access.log  main|g" /etc/nginx/nginx.conf
sed -i "s|keepalive_timeout   65|keepalive_timeout   ${NGINX_KEEPALIVE_TIMEOUT}|g" /etc/nginx/nginx.conf
sed -i "28a\    server_tokens       off;" /etc/nginx/nginx.conf
sed -i "29a\    #etag                off;" /etc/nginx/nginx.conf
vim /etc/nginx/nginx.conf
/usr/sbin/nginx -t
############################################################################
fi
#########################################
echo -e "Jp: Logrotate and Databaseをセットアップします。[y] / 既に一回このシェルを通している場合は [n]"
echo -e "En: You set up the Logrotate and Database. [y] / Already one time when it is passed through the shell [n]"
read set_db_and_logrotate
if [ ${set_db_and_logrotate} = "y" ] ; then
#########################################
####
echo "Logrotate Setup."
cat <<EOF > /etc/logrotate.d/webserver
/var/www/logs/*log {
    create 0644 ${WEB_SERVER_SYSTEM_USER_GROUP} ${WEB_SERVER_SYSTEM_USER_GROUP}
    daily
    rotate 10
    missingok
    notifempty
    sharedscripts
    delaycompress
    postrotate
        /bin/systemctl reload php-fpm.service > /dev/null 2>/dev/null || true
        /bin/kill -USR1 `cat /run/nginx.pid 2>/dev/null` 2>/dev/null || true
    endscript
}
EOF
vim /etc/logrotate.d/webserver
#### DB
echo -e "MariaDB conf Edit."
echo "default-storage-engine=${DB_STORAGE_ENGINE}" >> /etc/my.cnf
vim /etc/my.cnf
####
systemctl enable php-fpm
systemctl enable nginx
systemctl enable mariadb
systemctl start php-fpm
systemctl start nginx
systemctl start mariadb
####
mysql_secure_installation
####
rm -fr ${NGINX_BUILD_PATH}/rpm
rm -f ${NGINX_BUILD_PATH}/.rpmmacros
fi
## clamd cron setup
echo -e "Jp: clamavのインストールしている場合は [y] / インストールしていない場合は [n]"
echo -e "En: If you have installed the clamav [y] / If you do not have installed [n]"
read websvclamd
if [ ${websvclamd} = "y" ] ; then
cat <<EOF > /etc/cron.daily/public
#!/bin/bash
ExcludeDirectory=/etc/.clamav/exclude
if [ -s \$ExcludeDirectory ]; then
for i in \`cat \$ExcludeDirectory\`
do
if [ \$(echo "\$i"|grep \/$) ]; then
i=\`echo \$i|sed -e 's/^\([^ ]*\)\/$/\1/p' -e d\`
excludeopt="\${excludeopt} --exclude-dir=\$i"
else
excludeopt="\${excludeopt} --exclude=\$i"
fi
done
fi
yum -y update clamav > /dev/null 2>&1
freshclam > /dev/null
clamscan --recursive --remove ${excludeopt} /var/www >> /home/${USER_NAME}/logs/clamscan/clamscan_pub.log 2>&1
cd /home/${USER_NAME}/logs/clamscan
mv clamscan_pub.log clamscan_pub."\$(date +%Y%m%d-%I%M%S).txt"
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/logs/clamscan/*
EOF
#
chmod 700 /etc/cron.daily/public
vim /etc/cron.daily/public
fi
####
echo -e "WebServer Setup End."
####
